import page_home
import page_home_appearance

import page_home_devices
import page_home_devices_printers

import page_home_system
import page_home_network
import page_home_software


# import page_home_rpi_hardware